version: '3'

services:
  rabbitmq:
    container_name: rm_shopping
    image: rabbitmq:3-management
    restart: unless-stopped
    environment:
      - RABBITMQ_DEFAULT_USER=user 
      - RABBITMQ_DEFAULT_PASS=pwd
    volumes:
      - shoppingvol:/var/lib/rabbitmq 
    ports:
      - 5672:5672
      - 5673:5673
      - 15672:15672
      - 15674:15674
      - 15671:15671
    networks:
      - shopping 

networks:
  shopping:
    driver: bridge

volumes:
  shoppingvol:
    driver: local
